# -*- coding: utf-8 -*-
"""Experiment-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10u5YwahuXLZ22jjklR_4jHbx1nhnaDaJ

# HMS - Harmful Brain Activity Classification
"""

#! pip install focal-loss-torch

from bisect import bisect_left
import copy
import os
import pickle
import subprocess
import sys
import time
from tqdm import tqdm
import traceback
from concurrent.futures import ProcessPoolExecutor, as_completed, ThreadPoolExecutor
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn import CrossEntropyLoss
import torch.utils.data as data
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, TensorDataset, DataLoader
import torch.optim as optim
from focal_loss.focal_loss import FocalLoss

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.metrics import roc_auc_score, precision_recall_curve, cohen_kappa_score, classification_report

# modeling_wav2vec2.py variables and imports
from transformers.modeling_outputs import SequenceClassifierOutput
from transformers import Wav2Vec2ForSequenceClassification, Wav2Vec2Processor

from IPython.display import FileLink, display


print("Libraries imported successfully.")
config ={
    "use_ekg": False,
    "num_epochs": 100,
    "eeg_cols": [
         'Fp1', 'F3', 'C3', 'P3',
         'F7', 'T3', 'T5', 'O1', 'Fz',
         'Cz', 'Pz', 'Fp2', 'F4', 'C4',
         'P4', 'F8', 'T4', 'T6', 'O2',
    ],
    "batch_size":128,

    #partitions
    "partition_config":{
        #"partition_name": "small_partition",
        "partition_name": "complete",
        "select_full_confidence_only": False,
        "sample_fraction": 1,
        "fc_min_fraction": 0.5,
        "uniform_weights": False,
    },

    #model
    "model_name": "facebook/wav2vec2-base",

    #criterion
    "criterion_name":"crossentropy",
    "criterion_kwargs":{
        "gamma": 0.7,
    },
    "dataloader_num_workers": 4,
    "epoch_offset":12,
}

# BASE_DIR = "/kaggle/input/hms-harmful-brain-activity-classification/"
BASE_DIR = "/dgx001/debasisai/scholar/deepak/data/hms-harmful-brain-activity-classification/"
#BASE_DIR = "/dgx001/debasisai/scholar/deepak/data/hms-harmful-brain-activity-classification/"


raw_meta_df_path = os.path.join(BASE_DIR, "train.csv")
df = pd.read_csv(raw_meta_df_path)

target_encoding = {'Seizure':0, 'LPD':1, 'GPD':2, 'LRDA':3, 'GRDA':4, 'Other':5,
                   'seizure':0, 'lpd':1, 'gpd':2, 'lrda':3, 'grda':4, 'other':5,
                   0:'seizure', 1:'lpd', 2:'gpd', 3:'lrda', 4:'grda', 5:'other'}
total_targets = 6

votes=['seizure_vote', 'lpd_vote', 'gpd_vote', 'lrda_vote', 'grda_vote', 'other_vote']
normed_votes_columns=[col+"_normed" for col in votes]
votes_map={k.split('_')[0]:i for i,k in enumerate(votes)}
votes_map.update({i:k.split('_')[0] for i,k in enumerate(votes)})

#TODO - left to use eeg_cols as an experiment parameter
eeg_cols=config["eeg_cols"]
if config["use_ekg"]:
    eeg_cols.append("EKG")
num_channels=len(eeg_cols)

num_classes=6
sample_rate=200
sample_duration=50
batch_size = config["batch_size"]
max_pool_size=1000
dataloader_num_workers = config["dataloader_num_workers"]

model_folder_path="/kaggle/input/model_lstm/transformers/default/2"
model_path="/kaggle/input/model_lstm/transformers/default/2/model_6"
dataset_folder_path="/kaggle/input/model_lstm/transformers/default/2"
print(os.path.exists(model_folder_path))
print(os.path.exists(model_path))
print(os.path.exists(dataset_folder_path))

df['total_votes'] = df['seizure_vote']+df['lpd_vote']+df['gpd_vote']+df['lrda_vote']+df['grda_vote']+df['other_vote']
df['seizure_vote_normed'] = df['seizure_vote']/df['total_votes']
df['lpd_vote_normed'] = df['lpd_vote']/df['total_votes']
df['gpd_vote_normed'] = df['gpd_vote']/df['total_votes']
df['lrda_vote_normed'] = df['lrda_vote']/df['total_votes']
df['grda_vote_normed'] = df['grda_vote']/df['total_votes']
df['other_vote_normed'] = df['other_vote']/df['total_votes']



def get_col_ix(col_id): #Consistency checked
    if isinstance(col_id, int):
        return 9+col_id
    elif isinstance(col_id, str):
        return 9+target_encoding[col_id]

def get_vote_col(col_id): #Consistency checked
    if isinstance(col_id, int):
        return f'{target_encoding[col_id]}_vote'
    elif isinstance(col_id, str):
        return f'{col_id}_vote'

def get_normed_ix(col_id): #Consistency checked
    if isinstance(col_id, int):
        return 16+col_id
    elif isinstance(col_id, str):
        return 16+target_encoding[col_id]

def get_normed_col(col_id): #Consistency checked
    if isinstance(col_id, int):
        return f'{target_encoding[col_id]}_vote_normed'
    elif isinstance(col_id, str):
        return f'{col_id}_vote_normed'

def get_eeg_path(id):
    #eeg_path=eeg_path = f"/kaggle/input/hms-harmful-brain-activity-classification/train_eegs/{id}.parquet"
    return os.path.join(BASE_DIR, "train_eegs", f"{id}.parquet")
    return eeg_path

def get_eeg(id):

    eeg_path = get_eeg_path(id)
    if not os.path.exists(eeg_path):
        raise FileNotFoundError(f"EEG file not found at: {eeg_path}")
    eeg = pd.read_parquet(eeg_path)[eeg_cols]
    return eeg

def get_eeg_sample(ix, meta_df, return_normalized_votes=False):
    id=meta_df.loc[ix, 'eeg_id']
    eeg=get_eeg(id)
    start_frame=int(meta_df.loc[ix, 'eeg_label_offset_seconds']*200)
    end_frame=start_frame+10000
    eeg_sample=torch.from_numpy(eeg.iloc[start_frame: end_frame].to_numpy())
    if not return_normalized_votes:
        return eeg_sample
    normalized_votes = torch.from_numpy(meta_df.loc[ix, normed_votes_columns].to_numpy(dtype=np.float32))
    return normalized_votes, eeg_sample

def download_file(path, download_file_name):
    os.chdir('./')
    zip_name = f"/kaggle/working/{download_file_name}.zip"
    command = f"zip {zip_name} {path} -r"
    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        print("Unable to run zip command!")
        print(result.stderr)
        return
    display(FileLink(f'{download_file_name}.zip'))

def eeg_sample_isnan(ix, meta_df):
    eeg_sample = get_eeg_sample(ix, meta_df).transpose(0, 1)
    scaler = StandardScaler()
    eeg_sample = scaler.fit_transform(eeg_sample.T).T
    if np.isnan(eeg_sample).any():
        return ix
    return None

def prune_nans(meta_df):
    total_unpruned_rows = meta_df.shape[0]
    nan_indices = set()

    with ThreadPoolExecutor(max_workers=4) as executor:
        results = list(tqdm(executor.map(lambda idx: eeg_sample_isnan(idx, meta_df), range(total_unpruned_rows)),total=total_unpruned_rows))

    nan_indices = set(filter(None, results))
    ans_df=meta_df.loc[meta_df.index[~meta_df.index.isin(nan_indices)]].reset_index()
    return ans_df

df['confidence'] = df.apply(lambda row: row[get_normed_col(target_encoding[row['expert_consensus']])], axis=1)
df['full_confidence'] = (df['confidence'] > 0.999) & (df['confidence'] < 1.001)

bins = [i / 10 for i in range(11)]
bins[-1]+=0.01
labels = [(i+0.5)/10 for i in range(10)]
df['confidence_classes'] = pd.cut(df['confidence'], bins=bins, labels=labels, include_lowest=True)

meta_fc_df=df[df['full_confidence']]
meta_fc_df.drop(columns=['full_confidence', 'confidence_classes'], inplace=True)
meta_df = copy.deepcopy(df)

sample_fraction = config["partition_config"]["sample_fraction"]
fc_min_fraction = config["partition_config"]["fc_min_fraction"]
uniform_weights = config["partition_config"]["uniform_weights"]
select_full_confidence_only = config["partition_config"]["select_full_confidence_only"]

if select_full_confidence_only:
    meta_df = meta_fc_df.sample(frac=sample_fraction).reset_index(drop=True)
else:
    meta_df = meta_df.sample(frac=sample_fraction).reset_index(drop=True)

all_class_dfs=[]
for vote in votes:
    all_class_dfs.append(meta_df[meta_df[vote]>0.01])
counts=[class_df.shape[0] for class_df in all_class_dfs]
total_count=meta_df.shape[0]
weights = torch.tensor([count/total_count for count in counts])

if uniform_weights:
    fc_fraction = 1
    min_count=min(counts)
    print(min_count)
    len_samples=int(min_count*fc_fraction)
    all_samples=[sample_df.sample(n=len_samples, replace=True) for i,sample_df in enumerate(all_class_dfs)]
    meta_df = pd.concat(all_samples, ignore_index=True)
    weights = torch.tensor([1 for i in range(num_classes)])
total_count=meta_df.shape[0]

if config["partition_config"]["partition_name"]=="small_partition":
    meta_df=meta_df.sample(frac=0.01, ignore_index=True)

meta_df=prune_nans(meta_df)
print(f"meta_df.shape = ", meta_df.shape)

# Simplified Wav2Vec2 Model Loader (without BiLSTM)

_HIDDEN_STATES_START_POSITION = 2

class ModelLoader(Wav2Vec2ForSequenceClassification):
    loss_fct = None

    def __init__(self, config):
        super().__init__(config)

        if hasattr(config, "add_adapter") and config.add_adapter:
            raise ValueError(
                "Sequence classification does not support the use of Wav2Vec2 adapters (config.add_adapter=True)"
            )
        self.wav2vec2 = Wav2Vec2Model(config)
        num_layers = config.num_hidden_layers + 1  # transformer layers + input embeddings
        if config.use_weighted_layer_sum:
            self.layer_weights = nn.Parameter(torch.ones(num_layers) / num_layers)

        # Simple projector and classifier (without BiLSTM)
        self.projector = nn.Linear(config.hidden_size, config.classifier_proj_size)
        self.classifier = nn.Linear(config.classifier_proj_size, config.num_labels)

    @classmethod
    def from_pretrained(
        cls,
        pretrained_model_name_or_path,
        *model_args,
        config = None,
        cache_dir = None,
        ignore_mismatched_sizes = False,
        force_download = False,
        local_files_only = False,
        token = None,
        revision = "main",
        use_safetensors = None,
        criterion = None,
        **kwargs,
    ):
        if criterion is None:
            cls.loss_fct = CrossEntropyLoss()
        else:
            cls.loss_fct = criterion
        return Wav2Vec2ForSequenceClassification.from_pretrained(
            pretrained_model_name_or_path,
            *model_args,
            config = None,
            cache_dir = None,
            ignore_mismatched_sizes = False,
            force_download = False,
            local_files_only = False,
            token = None,
            revision = "main",
            use_safetensors = None,
            **kwargs,
        )

    def forward(
        self,
        input_values,
        attention_mask=None,
        output_attentions=None,
        output_hidden_states=None,
        return_dict=None,
        labels=None,
    ):
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict
        output_hidden_states = True if self.config.use_weighted_layer_sum else output_hidden_states

        outputs = self.wav2vec2(
            input_values,
            attention_mask=attention_mask,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
        )

        if self.config.use_weighted_layer_sum:
            hidden_states = outputs[_HIDDEN_STATES_START_POSITION]
            hidden_states = torch.stack(hidden_states, dim=1)
            norm_weights = nn.functional.softmax(self.layer_weights, dim=-1)
            hidden_states = (hidden_states * norm_weights.view(-1, 1, 1)).sum(dim=1)
        else:
            hidden_states = outputs[0]

        # Project features
        projected_states = self.projector(hidden_states)
        
        # Simple mean pooling over sequence
        if attention_mask is not None:
            # Expand attention mask to match feature dimension
            padding_mask = self._get_feature_vector_attention_mask(projected_states.shape[1], attention_mask)
            expand_padding_mask = padding_mask.unsqueeze(-1).repeat(1, 1, projected_states.shape[2])
            projected_states[~expand_padding_mask] = 0.0
            pooled_output = projected_states.sum(dim=1) / padding_mask.sum(dim=1).view(-1, 1)
        else:
            pooled_output = projected_states.mean(dim=1)

        # Final classification
        logits = self.classifier(pooled_output)

        loss = None
        if labels is not None:
            loss = ModelLoader.loss_fct(logits.view(-1, self.config.num_labels), labels.view(-1))

        if not return_dict:
            output = (logits,) + outputs[_HIDDEN_STATES_START_POSITION:]
            return ((loss,) + output) if loss is not None else output

        return SequenceClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )

# Model and Processor

processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base")

# Fix for CrossEntropyLoss - Don't pass criterion_kwargs if using CrossEntropyLoss

# Criterion Selection Logic
criterion = None
if config["criterion_name"] == "focal":
    criterion = FocalLoss(weights=weights, **config["criterion_kwargs"])
elif config["criterion_name"] in ["crossentropy", "focal_vat"]:
    # Using weight=weights handles class imbalance in the HMS dataset
    criterion = CrossEntropyLoss(weight=weights)
else:
    raise NotImplementedError(f"Criterion {config['criterion_name']} not supported.")

# Model Initialization
# Pass the 'criterion' variable defined above to the loader
model = ModelLoader.from_pretrained(
    pretrained_model_name_or_path="facebook/wav2vec2-base",
    num_labels=num_classes,
    criterion=criterion  # <--- Changed from FocalLoss(gamma=0.7...)
)

# Load existing weights if path exists
if os.path.exists(model_folder_path):
    print(f"Loading checkpoint from: {model_path}")
    model = ModelLoader.from_pretrained(
        pretrained_model_name_or_path=model_path,
        num_labels=num_classes,
        criterion=criterion # Ensure the loaded model also uses the correct loss
    )

# Freeze feature extractor (Wav2Vec2 CNN backbone)
# This is critical for stable training when fine-tuning on EEG data
for param in model.wav2vec2.feature_extractor.parameters():
    param.requires_grad = False

time.sleep(3)

# Splitting and creating partitions
if (not os.path.isdir(dataset_folder_path)):
    if not config["partition_config"]["partition_name"]=="patient_agnostic":
        len_meta_df=meta_df.shape[0]
        test_frac=0.1
        val_frac=0.1
        train_meta_df=meta_df.iloc[:int((1-test_frac-val_frac)*len_meta_df),:]
        val_meta_df=meta_df.iloc[int((1-test_frac-val_frac)*len_meta_df):int((1-test_frac)*len_meta_df),:]
        test_meta_df=meta_df.iloc[int((1-test_frac)*len_meta_df):, :]
        pool_size = int((max_pool_size//batch_size)*batch_size)
    else:
        test_fraction = 0.1
        validation_fraction = 0.1
        patient_group=meta_df.groupby("patient_id", as_index=False).agg({"eeg_id":"count"})
        patient_group.sample(frac=1).reset_index(drop=True)
        patient_group.rename(columns={"eeg_id":"count"}, inplace=True)
        patient_group["cumulative_count"]=patient_group["count"].cumsum()

        len_meta_df=meta_df.shape[0]
        train_samples=(1-test_fraction-validation_fraction)*len_meta_df
        last_train_patient=patient_group['cumulative_count'].searchsorted(train_samples, side='right')
        train_meta_df=meta_df[meta_df['patient_id'].isin(patient_group.loc[:last_train_patient, 'patient_id'])]

        validation_samples=validation_fraction*len_meta_df
        last_validation_patient=patient_group['cumulative_count'].searchsorted(train_samples+validation_samples, side='right')
        val_meta_df=meta_df[meta_df['patient_id'].isin(patient_group.loc[last_train_patient+1:last_validation_patient, 'patient_id'])]

        last_test_patient=patient_group['cumulative_count'].searchsorted(len_meta_df, side='right')
        test_meta_df=meta_df[meta_df['patient_id'].isin(patient_group.loc[last_validation_patient+1:last_test_patient, 'patient_id'])]

    train_meta_df.to_csv("train_meta_df.csv")
    test_meta_df.to_csv("test_meta_df.csv")
    val_meta_df.to_csv("val_meta_df.csv")

else:
    train_meta_path=dataset_folder_path+"/train_meta_df.csv"
    val_meta_path=dataset_folder_path+"/val_meta_df.csv"
    test_meta_path=dataset_folder_path+"/test_meta_df.csv"

    test_meta_df=pd.read_csv(test_meta_path)
    train_meta_df=pd.read_csv(train_meta_path)
    val_meta_df=pd.read_csv(val_meta_path)
    print("Saved path for meta_dfs loaded")

# ------------------------------------------------------------------
# Inspect dataset splits
# ------------------------------------------------------------------
print("\n===== Dataset Split Summary =====")

print(f"Train meta df shape: {train_meta_df.shape}")
print(f"Val   meta df shape: {val_meta_df.shape}")
print(f"Test  meta df shape: {test_meta_df.shape}")

print("\n----- Percentage split -----")
total = len(train_meta_df) + len(val_meta_df) + len(test_meta_df)
print(f"Train: {len(train_meta_df)/total:.2%}")
print(f"Val  : {len(val_meta_df)/total:.2%}")
print(f"Test : {len(test_meta_df)/total:.2%}")

# Optional: sanity check for patient-agnostic split
if "patient_id" in meta_df.columns:
    train_patients = set(train_meta_df["patient_id"])
    val_patients   = set(val_meta_df["patient_id"])
    test_patients  = set(test_meta_df["patient_id"])

    print("\n----- Patient overlap check -----")
    print("Train ∩ Val :", len(train_patients & val_patients))
    print("Train ∩ Test:", len(train_patients & test_patients))
    print("Val   ∩ Test:", len(val_patients & test_patients))

# Custom Dataset Class
class EEGDataset(Dataset):
    def __init__(self, meta_df, pool_size, name, processor=processor, target_sampling_rate=16000, orig_sampling_rate=200):
        # super().__init__(meta_df, pool_size, name)
        self.pool_size = pool_size
        self.meta_df = meta_df
        self.name = name
        self.processor = processor
        self.orig_sampling_rate = orig_sampling_rate
        self.target_sampling_rate = target_sampling_rate

        self.scaler = StandardScaler()
        print(f"EEGDataset {name} initialized\n")

    def __len__(self):
        return self.meta_df.shape[0]

    def __getitem__(self, idx):
        ix=idx
        normalized_vote, eeg_sample = get_eeg_sample(ix, self.meta_df, True)
        eeg_sample = eeg_sample.transpose(0, 1)
        eeg_sample = self.scaler.fit_transform(eeg_sample.T).T
        label = votes_map[self.meta_df.loc[ix, 'expert_consensus'].lower()]
        inputs = self.processor(eeg_sample, sampling_rate=self.target_sampling_rate, return_tensors="pt", padding=True)
        inputs["labels"] = torch.tensor(label, dtype=torch.long)
        inputs["normalized_votes"] = normalized_vote
        return inputs

pool_size=(max_pool_size//batch_size)*batch_size

train_meta_df.reset_index(drop=True, inplace=True)
val_meta_df.reset_index(drop=True, inplace=True)
test_meta_df.reset_index(drop=True, inplace=True)

if (not os.path.isdir(dataset_folder_path)):
    train_dataset = EEGDataset(train_meta_df, pool_size, "train")
    val_dataset = EEGDataset(val_meta_df, pool_size, "val")
    test_dataset = EEGDataset(test_meta_df, pool_size, "test")
else:
    train_dataset=EEGDataset(train_meta_df, pool_size, "train")
    test_dataset=EEGDataset(test_meta_df, pool_size, "test")
    val_dataset=EEGDataset(val_meta_df, pool_size, "val")

train_loader = DataLoader(train_dataset, batch_size=batch_size, prefetch_factor=1, pin_memory=True, num_workers=dataloader_num_workers, persistent_workers=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, prefetch_factor=1, pin_memory=True, num_workers=dataloader_num_workers, persistent_workers=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, prefetch_factor=1, pin_memory=True, num_workers=dataloader_num_workers, persistent_workers=True)

# Optimizer and Loss
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-5)
num_epochs=config["num_epochs"]
epoch_offset=config["epoch_offset"]

class EvaluatePartition:
    def __init__(self, model, data_loader, name, device=device):
        self.model=model
        self.data_loader=data_loader
        self.name=name
        self.device=device

        self.calc_softmax=torch.nn.Softmax(dim=-1)
        self.data_preds = []
        self.data_labels = []
        self.data_probs = []
        self.total_loss = 0.0
        self.total_kl_loss = 0.0
        self.num_classes = None
        self.final_metrics = {}


    def _reset_base_metrics(self, base_metrics=None):
        self.data_preds = []
        self.data_labels = []
        self.data_probs = []
        self.total_loss = 0.0
        self.total_kl_loss = 0.0
        if base_metrics is not None:
            self.data_preds = base_metrics["data_preds"]
            self.data_labels = base_metrics["data_labels"]
            self.data_probs = base_metrics["data_probs"]
            self.total_loss = base_metrics["total_loss"]
            self.total_kl_loss = base_metrics["total_kl_loss"]
        self.final_metrics.clear()

    def _evaluate(self, base_metrics=None):
        self._reset_base_metrics(base_metrics)

        if base_metrics is None:
            with torch.no_grad():
                for batch in tqdm(self.data_loader, desc=f"Checking model on {self.name} dataset", ncols=100, leave=True, dynamic_ncols=True):
                    inputs=self._get_input_kwargs(batch)
                    normalized_votes=inputs['normalized_votes']
                    del inputs['normalized_votes']

                    outputs = self.model(**inputs)

                    inputs['normalized_votes']=normalized_votes
                    loss=outputs.loss
                    self.total_loss+=loss.item()
                    logits, preds, probs, labels = self._process_model_outputs(inputs, outputs)

        return self._get_final_metrics()

    def _get_input_kwargs(self, batch):
        inputs = {}
        inputs['input_values'] = batch['input_values'].to(torch.float32).to(self.device)
        if len(inputs['input_values'].shape) == 1:
            inputs['input_values'] = torch.unsqueeze(inputs['input_values'], 0)
            inputs['input_values'].to(self.device)
        inputs['input_values'] = torch.reshape(inputs['input_values'], (-1, num_channels*10000))
        inputs['labels'] = batch['labels'].to(torch.int64).to(self.device)
        inputs['normalized_votes']=batch['normalized_votes'].to(self.device)
        return inputs

    def _process_model_outputs(self, inputs, outputs):
        logits = outputs.logits
        # Collect predictions and labels
        preds = torch.argmax(logits, dim=-1)
        self.data_preds.extend(preds.tolist())

        labels = inputs['labels']
        self.data_labels.extend(labels.tolist())

        probs = self.calc_softmax(logits)
        self.data_probs.append(probs.detach().cpu().numpy())

        # print("probabilities = ", F.log_softmax(logits, dim=-1))
        # print("log probabilities = ", torch.log(F.log_softmax(logits, dim=-1)))
        kl_loss = F.kl_div(F.log_softmax(logits, dim=-1), inputs['normalized_votes'], reduction='batchmean')
        self.total_kl_loss += kl_loss.item()

        return logits, preds, probs, labels

    def _get_final_metrics(self, base_metrics=None):
        self._finalize_epoch_data()
        self.num_classes = self.data_probs.shape[1]
        self._add_regressive_scores()
        self._add_evaluation_graphs()
        return self.final_metrics

    def _finalize_epoch_data(self):
        self.data_labels = torch.tensor(self.data_labels).cpu().numpy()
        self.data_preds = torch.tensor(self.data_preds).cpu().numpy()
        if isinstance(self.data_probs, list):
            self.data_probs = np.concatenate(self.data_probs, axis=0)
        self.data_probs = torch.tensor(self.data_probs).cpu().numpy()

    def _add_regressive_scores(self):
        data_accuracy = accuracy_score(self.data_labels, self.data_preds)
        data_f1 = f1_score(self.data_labels, self.data_preds, average='weighted')
        data_precision = precision_score(self.data_labels, self.data_preds, average='weighted')
        data_recall = recall_score(self.data_labels, self.data_preds, average='weighted')
        cohen_kappa = cohen_kappa_score(self.data_labels, self.data_preds)

        regressive_scores={
            "accuracy": data_accuracy,
            "f1_score": data_f1,
            "precision": data_precision,
            "recall": data_recall,
            "cohen_kappa": cohen_kappa,
            "total_loss": self.total_loss,
            "total_kl_loss": self.total_kl_loss,
        }
        print(f"{self.name} Dataset - Accuracy: {data_accuracy:.4f} | Precision: {data_precision:.4f} | Recall: {data_recall:.4f} | F1: {data_f1:.4f}")
        print(f"Total Loss: {self.total_loss:.4f} | Total KL Loss: {self.total_kl_loss:.4f} | cohen_kappa: {cohen_kappa:.4f}")
        self.final_metrics.update(regressive_scores)

    def _add_evaluation_graphs(self):
        try:
            auc_roc = roc_auc_score(self.data_labels, self.data_probs, multi_class='ovr', average='weighted')
        except ValueError:
            auc_roc = None

        pr_curves = {}
        for i in range(self.num_classes):
            precision, recall, _ = precision_recall_curve(self.data_labels == i, self.data_probs[:, i])
            pr_curves[f"class_{i}"] = {"precision": precision.tolist(), "recall": recall.tolist()}
        class_report = classification_report(self.data_labels, self.data_preds, output_dict=True)

        evaluation_curves={
            "auc_roc": auc_roc,
            "support": class_report["weighted avg"]["support"],
            "pr_curves": pr_curves
        }
        self.final_metrics.update(evaluation_curves)

# # Training Loop - EvaluatePartition based with Early Stopping
final_data_path = "./experiment_data.pkl"
if os.path.exists(os.path.join(model_folder_path, final_data_path)):
    with open(os.path.join(model_folder_path, final_data_path), 'rb') as f:
        experiment_data = pickle.load(f)
else:
    experiment_data={}
    experiment_data["experiment_config"] = config

training = EvaluatePartition(model = model, data_loader = train_loader, name="train", device=device)
validation = EvaluatePartition(model = model, data_loader = val_loader, name="val", device=device)
testing = EvaluatePartition(model = model, data_loader = test_loader, name="test", device=device)

best_val_acc = -float("inf")
best_model_path = "model_best"

# ============ Early Stopping Parameters ============
patience = 15  # Number of epochs to wait for improvement
epochs_without_improvement = 0
early_stopping_enabled = True
# ==================================================

for epoch_id in range(num_epochs):
    epoch=epoch_id+epoch_offset
    model.train()
    total_loss = 0.0
    total_kl_loss = 0.0
    train_preds, train_labels, train_probs = [], [], []
    
    training._reset_base_metrics()
    print(f"For Epoch: {epoch}")
    epoch_data={
        f"{training.name}_metrics":{},
        f"{validation.name}_metrics":{},
        f"{testing.name}_metrics":{},
    }
    
    for i, batch in enumerate(tqdm(train_loader)):
        inputs = training._get_input_kwargs(batch)
        normalized_votes=inputs['normalized_votes']
        del inputs['normalized_votes']
        
        outputs = model(**inputs)
        inputs['normalized_votes']=normalized_votes
        
        loss = outputs.loss
        training.total_loss += loss.item()
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()        
        training._process_model_outputs(inputs, outputs)
        
    train_metrics = training._get_final_metrics()
    val_metrics = validation._evaluate()
    test_metrics = testing._evaluate()
    
    epoch_data[f"{training.name}_metrics"].update(train_metrics)
    epoch_data[f"{validation.name}_metrics"].update(val_metrics)
    epoch_data[f"{testing.name}_metrics"].update(test_metrics)
    experiment_data[f"epoch_{epoch}"] = {}
    experiment_data[f"epoch_{epoch}"].update(epoch_data)
    
    current_val_acc = val_metrics["accuracy"]
    
    # ============ Early Stopping Logic ============
    if current_val_acc > best_val_acc:
        best_val_acc = current_val_acc
        epochs_without_improvement = 0  # Reset counter
        model.save_pretrained(best_model_path)
        print(f"Model saved (new best val accuracy: {best_val_acc:.4f})")
    else:
        epochs_without_improvement += 1
        print(f"No improvement in validation accuracy. Epochs without improvement: {epochs_without_improvement}/{patience}")
        
        # Check if early stopping criteria is met
        if early_stopping_enabled and epochs_without_improvement >= patience:
            print(f"\n{'='*60}")
            print(f"Early stopping triggered!")
            print(f"Best validation accuracy: {best_val_acc:.4f}")
            print(f"Training stopped at epoch {epoch} after {patience} epochs without improvement")
            print(f"{'='*60}\n")
            
            # Save experiment data before exiting
            with open(final_data_path, 'wb') as f:
                pickle.dump(experiment_data, f)
            print(f"experiment_data variable saved in {final_data_path}")
            break  # Exit training loop
    # ==========================================
    
    with open(final_data_path, 'wb') as f:
        pickle.dump(experiment_data, f)
    print(f"experiment_data variable saved and updated in {final_data_path}")
    print()



# ===================== COMPREHENSIVE FINAL EVALUATION & VISUALIZATION =====================
# Research-Grade Analysis with Multiple Publication-Ready Figures

import os
import json
import pickle
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.gridspec import GridSpec
import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    precision_recall_fscore_support,
    roc_curve,
    auc,
    roc_auc_score,
    cohen_kappa_score,
    matthews_corrcoef,
    hamming_loss,
    precision_recall_curve,
    f1_score
)
from sklearn.manifold import TSNE
from scipy import stats

# Set style for publication-ready figures
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
RESULTS_DIR = "./final_results"
FIGURES_DIR = os.path.join(RESULTS_DIR, "figures")
METRICS_DIR = os.path.join(RESULTS_DIR, "metrics")
TABLES_DIR = os.path.join(RESULTS_DIR, "tables")

os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(FIGURES_DIR, exist_ok=True)
os.makedirs(METRICS_DIR, exist_ok=True)
os.makedirs(TABLES_DIR, exist_ok=True)

print("="*80)
print("RESEARCH-GRADE COMPREHENSIVE EVALUATION & VISUALIZATION")
print("="*80)

# ---------------------------------------------------------------------------
# Load best model
# ---------------------------------------------------------------------------
print("\n[1/12] Loading best model...")
model = ModelLoader.from_pretrained("model_best")
model.to(device)
model.eval()
print("✅ Model loaded successfully")

# ---------------------------------------------------------------------------
# Final Test Evaluation
# ---------------------------------------------------------------------------
print("\n[2/12] Performing final test evaluation...")
test_partition = EvaluatePartition(
    model=model,
    data_loader=test_loader,
    name="test",
    device=device
)

test_partition._reset_base_metrics()
test_metrics = test_partition._evaluate()
print("✅ Test evaluation complete")

# Extract predictions & labels
y_true = test_partition.data_labels
y_pred = test_partition.data_preds
y_probs = test_partition.data_probs

print(f"   y_true shape: {y_true.shape}")
print(f"   y_pred shape: {y_pred.shape}")
print(f"   y_probs shape: {y_probs.shape}")

np.save(os.path.join(METRICS_DIR, "y_true.npy"), y_true)
np.save(os.path.join(METRICS_DIR, "y_pred.npy"), y_pred)
np.save(os.path.join(METRICS_DIR, "y_probs.npy"), y_probs)

# ---------------------------------------------------------------------------
# Extract Training History
# ---------------------------------------------------------------------------
print("\n[3/12] Extracting training history...")
epochs, train_acc, val_acc, test_acc = [], [], [], []
train_loss, val_loss, test_loss = [], [], []
train_f1, val_f1, test_f1 = [], [], []
train_kappa, val_kappa, test_kappa = [], [], []

for k, v in experiment_data.items():
    if k.startswith("epoch_"):
        epochs.append(int(k.split("_")[1]))
        
        # Accuracy
        train_acc.append(v["train_metrics"]["accuracy"])
        val_acc.append(v["val_metrics"]["accuracy"])
        test_acc.append(v["test_metrics"]["accuracy"])
        
        # Loss
        train_loss.append(v["train_metrics"]["total_loss"])
        val_loss.append(v["val_metrics"]["total_loss"])
        test_loss.append(v["test_metrics"]["total_loss"])
        
        # F1 Score
        train_f1.append(v["train_metrics"]["f1_score"])
        val_f1.append(v["val_metrics"]["f1_score"])
        test_f1.append(v["test_metrics"]["f1_score"])
        
        # Cohen Kappa
        train_kappa.append(v["train_metrics"]["cohen_kappa"])
        val_kappa.append(v["val_metrics"]["cohen_kappa"])
        test_kappa.append(v["test_metrics"]["cohen_kappa"])

# Convert to numpy arrays
epochs = np.array(epochs)
train_acc, val_acc, test_acc = np.array(train_acc), np.array(val_acc), np.array(test_acc)
train_loss, val_loss, test_loss = np.array(train_loss), np.array(val_loss), np.array(test_loss)
train_f1, val_f1, test_f1 = np.array(train_f1), np.array(val_f1), np.array(test_f1)
train_kappa, val_kappa, test_kappa = np.array(train_kappa), np.array(val_kappa), np.array(test_kappa)

print(f"✅ Training history extracted: {len(epochs)} epochs")

# ---------------------------------------------------------------------------
# FIGURE 1: Combined Accuracy & Loss Curves (Train/Val/Test)
# ---------------------------------------------------------------------------
print("\n[4/12] Generating Figure 1: Accuracy & Loss Curves...")
fig = plt.figure(figsize=(16, 6))
gs = GridSpec(1, 2, figure=fig, hspace=0.3, wspace=0.3)

# Accuracy curve
ax1 = fig.add_subplot(gs[0, 0])
ax1.plot(epochs, train_acc, 'o-', linewidth=2.5, markersize=6, label='Train Acc', color='#2E86AB')
ax1.plot(epochs, val_acc, 's-', linewidth=2.5, markersize=6, label='Val Acc', color='#A23B72')
ax1.plot(epochs, test_acc, '^-', linewidth=2.5, markersize=6, label='Test Acc', color='#F18F01')
ax1.set_xlabel('Epoch', fontsize=12, fontweight='bold')
ax1.set_ylabel('Accuracy', fontsize=12, fontweight='bold')
ax1.set_title('Model Accuracy Over Epochs', fontsize=14, fontweight='bold')
ax1.legend(fontsize=11, loc='best', framealpha=0.95)
ax1.grid(True, alpha=0.4, linestyle='--')
ax1.set_ylim([0, 1.05])

# Loss curve
ax2 = fig.add_subplot(gs[0, 1])
ax2.plot(epochs, train_loss, 'o-', linewidth=2.5, markersize=6, label='Train Loss', color='#2E86AB')
ax2.plot(epochs, val_loss, 's-', linewidth=2.5, markersize=6, label='Val Loss', color='#A23B72')
ax2.plot(epochs, test_loss, '^-', linewidth=2.5, markersize=6, label='Test Loss', color='#F18F01')
ax2.set_xlabel('Epoch', fontsize=12, fontweight='bold')
ax2.set_ylabel('Loss', fontsize=12, fontweight='bold')
ax2.set_title('Model Loss Over Epochs', fontsize=14, fontweight='bold')
ax2.legend(fontsize=11, loc='best', framealpha=0.95)
ax2.grid(True, alpha=0.4, linestyle='--')

plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "01_accuracy_loss_curves.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "01_accuracy_loss_curves.pdf"), bbox_inches='tight')
plt.close()
print("✅ Figure 1 saved")

# ---------------------------------------------------------------------------
# FIGURE 2: F1 Score & Cohen Kappa Curves
# ---------------------------------------------------------------------------
print("\n[5/12] Generating Figure 2: F1 Score & Cohen Kappa Curves...")
fig = plt.figure(figsize=(16, 6))
gs = GridSpec(1, 2, figure=fig, hspace=0.3, wspace=0.3)

# F1 Score
ax1 = fig.add_subplot(gs[0, 0])
ax1.plot(epochs, train_f1, 'o-', linewidth=2.5, markersize=6, label='Train F1', color='#2E86AB')
ax1.plot(epochs, val_f1, 's-', linewidth=2.5, markersize=6, label='Val F1', color='#A23B72')
ax1.plot(epochs, test_f1, '^-', linewidth=2.5, markersize=6, label='Test F1', color='#F18F01')
ax1.set_xlabel('Epoch', fontsize=12, fontweight='bold')
ax1.set_ylabel('F1 Score', fontsize=12, fontweight='bold')
ax1.set_title('Weighted F1 Score Over Epochs', fontsize=14, fontweight='bold')
ax1.legend(fontsize=11, loc='best', framealpha=0.95)
ax1.grid(True, alpha=0.4, linestyle='--')
ax1.set_ylim([0, 1.05])

# Cohen Kappa
ax2 = fig.add_subplot(gs[0, 1])
ax2.plot(epochs, train_kappa, 'o-', linewidth=2.5, markersize=6, label='Train κ', color='#2E86AB')
ax2.plot(epochs, val_kappa, 's-', linewidth=2.5, markersize=6, label='Val κ', color='#A23B72')
ax2.plot(epochs, test_kappa, '^-', linewidth=2.5, markersize=6, label='Test κ', color='#F18F01')
ax2.set_xlabel('Epoch', fontsize=12, fontweight='bold')
ax2.set_ylabel("Cohen's Kappa", fontsize=12, fontweight='bold')
ax2.set_title("Cohen's Kappa Over Epochs", fontsize=14, fontweight='bold')
ax2.legend(fontsize=11, loc='best', framealpha=0.95)
ax2.grid(True, alpha=0.4, linestyle='--')

plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "02_f1_kappa_curves.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "02_f1_kappa_curves.pdf"), bbox_inches='tight')
plt.close()
print("✅ Figure 2 saved")

# ---------------------------------------------------------------------------
# FIGURE 3: Confusion Matrix
# ---------------------------------------------------------------------------
print("\n[6/12] Generating Figure 3: Confusion Matrix...")
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(10, 8))
class_names = [target_encoding[i] for i in range(num_classes)]
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=True, 
            xticklabels=class_names, yticklabels=class_names,
            cbar_kws={'label': 'Count'}, square=True, linewidths=0.5)
plt.xlabel("Predicted Label", fontsize=12, fontweight='bold')
plt.ylabel("True Label", fontsize=12, fontweight='bold')
plt.title("Confusion Matrix - Test Set", fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "03_confusion_matrix.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "03_confusion_matrix.pdf"), bbox_inches='tight')
plt.close()
print("✅ Figure 3 saved")

# ---------------------------------------------------------------------------
# FIGURE 4: Normalized Confusion Matrix
# ---------------------------------------------------------------------------
print("\n[7/12] Generating Figure 4: Normalized Confusion Matrix...")
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

plt.figure(figsize=(10, 8))
sns.heatmap(cm_normalized, annot=True, fmt=".2%", cmap="RdYlGn", cbar=True,
            xticklabels=class_names, yticklabels=class_names,
            cbar_kws={'label': 'Recall (%)'}, square=True, linewidths=0.5, vmin=0, vmax=1)
plt.xlabel("Predicted Label", fontsize=12, fontweight='bold')
plt.ylabel("True Label", fontsize=12, fontweight='bold')
plt.title("Normalized Confusion Matrix (Recall) - Test Set", fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "04_confusion_matrix_normalized.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "04_confusion_matrix_normalized.pdf"), bbox_inches='tight')
plt.close()
print("✅ Figure 4 saved")

# ---------------------------------------------------------------------------
# FIGURE 5: Per-Class Metrics Bar Plot
# ---------------------------------------------------------------------------
print("\n[8/12] Generating Figure 5: Per-Class Metrics...")
report = classification_report(y_true, y_pred, output_dict=True, zero_division=0)

classes = list(range(num_classes))
f1_scores = [report[str(i)]['f1-score'] for i in classes]
precisions = [report[str(i)]['precision'] for i in classes]
recalls = [report[str(i)]['recall'] for i in classes]
supports = [report[str(i)]['support'] for i in classes]

fig, ax = plt.subplots(figsize=(14, 7))
x = np.arange(len(classes))
width = 0.25

bars1 = ax.bar(x - width, precisions, width, label='Precision', alpha=0.85, color='#2E86AB', edgecolor='black', linewidth=1.2)
bars2 = ax.bar(x, recalls, width, label='Recall', alpha=0.85, color='#A23B72', edgecolor='black', linewidth=1.2)
bars3 = ax.bar(x + width, f1_scores, width, label='F1-Score', alpha=0.85, color='#F18F01', edgecolor='black', linewidth=1.2)

# Add value labels on bars
for bars in [bars1, bars2, bars3]:
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold')

ax.set_xlabel('Class', fontsize=12, fontweight='bold')
ax.set_ylabel('Score', fontsize=12, fontweight='bold')
ax.set_title('Per-Class Performance Metrics', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(class_names, rotation=45, ha='right')
ax.legend(fontsize=11, loc='lower right')
ax.grid(True, alpha=0.3, axis='y', linestyle='--')
ax.set_ylim([0, 1.15])

plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "05_per_class_metrics.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "05_per_class_metrics.pdf"), bbox_inches='tight')
plt.close()
print("✅ Figure 5 saved")

# ---------------------------------------------------------------------------
# FIGURE 6: ROC Curves (One-vs-Rest)
# ---------------------------------------------------------------------------
print("\n[9/12] Generating Figure 6: ROC Curves...")
fig, ax = plt.subplots(figsize=(10, 9))

colors = plt.cm.tab10(np.linspace(0, 1, num_classes))
roc_aucs = {}

for i in range(num_classes):
    y_bin = (y_true == i).astype(int)
    fpr, tpr, _ = roc_curve(y_bin, y_probs[:, i])
    roc_auc = auc(fpr, tpr)
    roc_aucs[class_names[i]] = roc_auc
    
    ax.plot(fpr, tpr, color=colors[i], lw=2.5,
            label=f'{class_names[i]} (AUC = {roc_auc:.3f})',
            alpha=0.8)

ax.plot([0, 1], [0, 1], 'k--', lw=2, label='Random Classifier', alpha=0.5)
ax.set_xlabel('False Positive Rate', fontsize=12, fontweight='bold')
ax.set_ylabel('True Positive Rate', fontsize=12, fontweight='bold')
ax.set_title('ROC Curves (One-vs-Rest)', fontsize=14, fontweight='bold')
ax.legend(fontsize=10, loc='lower right', framealpha=0.95)
ax.grid(True, alpha=0.3, linestyle='--')
ax.set_xlim([-0.02, 1.02])
ax.set_ylim([-0.02, 1.02])

plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "06_roc_curves.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "06_roc_curves.pdf"), bbox_inches='tight')
plt.close()
print("✅ Figure 6 saved")

# ---------------------------------------------------------------------------
# FIGURE 7: Precision-Recall Curves
# ---------------------------------------------------------------------------
print("\n[10/12] Generating Figure 7: Precision-Recall Curves...")
fig, ax = plt.subplots(figsize=(10, 9))

colors = plt.cm.tab10(np.linspace(0, 1, num_classes))

for i in range(num_classes):
    y_bin = (y_true == i).astype(int)
    precision, recall, _ = precision_recall_curve(y_bin, y_probs[:, i])
    pr_auc = auc(recall, precision)
    
    ax.plot(recall, precision, color=colors[i], lw=2.5,
            label=f'{class_names[i]} (AUC = {pr_auc:.3f})',
            alpha=0.8)

ax.set_xlabel('Recall', fontsize=12, fontweight='bold')
ax.set_ylabel('Precision', fontsize=12, fontweight='bold')
ax.set_title('Precision-Recall Curves', fontsize=14, fontweight='bold')
ax.legend(fontsize=10, loc='best', framealpha=0.95)
ax.grid(True, alpha=0.3, linestyle='--')
ax.set_xlim([-0.02, 1.02])
ax.set_ylim([-0.02, 1.02])

plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "07_precision_recall_curves.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "07_precision_recall_curves.pdf"), bbox_inches='tight')
plt.close()
print("✅ Figure 7 saved")

# ---------------------------------------------------------------------------
# FIGURE 8: t-SNE Visualization
# ---------------------------------------------------------------------------
print("\n[11/12] Generating Figure 8: t-SNE Visualization...")
print("   Extracting embeddings...")
embeddings = []
labels_list = []

with torch.no_grad():
    for batch in tqdm(test_loader, desc="   Extracting embeddings", leave=False):
        inputs = test_partition._get_input_kwargs(batch)
        
        outputs = model(
            input_values=inputs['input_values'],
            attention_mask=None,
            output_hidden_states=True,
            return_dict=True
        )
        
        if hasattr(outputs, 'hidden_states') and outputs.hidden_states is not None:
            emb = outputs.hidden_states[-1].mean(dim=1)
        else:
            emb = outputs.logits
            
        embeddings.append(emb.cpu().numpy())
        labels_list.append(inputs["labels"].cpu().numpy())

embeddings = np.concatenate(embeddings, axis=0)
labels_array = np.concatenate(labels_list, axis=0)

np.save(os.path.join(METRICS_DIR, "tsne_embeddings.npy"), embeddings)
np.save(os.path.join(METRICS_DIR, "tsne_labels.npy"), labels_array)

print("   Running t-SNE...")
perplexity_val = min(30, (embeddings.shape[0] - 1) // 3)
tsne = TSNE(n_components=2, perplexity=perplexity_val, random_state=42, max_iter=1500, verbose=0)
emb_2d = tsne.fit_transform(embeddings)

plt.figure(figsize=(12, 10))
scatter = plt.scatter(emb_2d[:, 0], emb_2d[:, 1], c=labels_array, cmap="tab10",
                     alpha=0.7, s=80, edgecolors='black', linewidth=0.5)
cbar = plt.colorbar(scatter, label='Class')
cbar.set_ticks(range(num_classes))
cbar.set_ticklabels(class_names)
plt.title('t-SNE Visualization of Test Data Embeddings', fontsize=14, fontweight='bold')
plt.xlabel('Dimension 1', fontsize=12, fontweight='bold')
plt.ylabel('Dimension 2', fontsize=12, fontweight='bold')
plt.grid(True, alpha=0.3, linestyle='--')
plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "08_tsne_visualization.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "08_tsne_visualization.pdf"), bbox_inches='tight')
plt.close()
print("✅ Figure 8 saved")

# ---------------------------------------------------------------------------
# FIGURE 9: Class Distribution
# ---------------------------------------------------------------------------
print("\n[12/12] Generating Figure 9: Class Distribution...")
unique, counts = np.unique(y_true, return_counts=True)
class_dist = {class_names[int(u)]: counts[i] for i, u in enumerate(unique)}

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

# Bar plot
colors_bar = plt.cm.tab10(np.linspace(0, 1, len(unique)))
bars = ax1.bar(range(len(unique)), counts, color=colors_bar, edgecolor='black', linewidth=1.5, alpha=0.85)
ax1.set_xlabel('Class', fontsize=12, fontweight='bold')
ax1.set_ylabel('Number of Samples', fontsize=12, fontweight='bold')
ax1.set_title('Class Distribution in Test Set', fontsize=14, fontweight='bold')
ax1.set_xticks(range(len(unique)))
ax1.set_xticklabels([class_names[int(u)] for u in unique], rotation=45, ha='right')
ax1.grid(True, alpha=0.3, axis='y', linestyle='--')

# Add value labels
for bar in bars:
    height = bar.get_height()
    ax1.text(bar.get_x() + bar.get_width()/2., height,
            f'{int(height)}', ha='center', va='bottom', fontsize=10, fontweight='bold')

# Pie plot
ax2.pie(counts, labels=[class_names[int(u)] for u in unique], autopct='%1.1f%%',
        colors=colors_bar, startangle=90, textprops={'fontsize': 11, 'weight': 'bold'},
        wedgeprops={'edgecolor': 'black', 'linewidth': 1.5})
ax2.set_title('Class Distribution (Percentage)', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "09_class_distribution.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "09_class_distribution.pdf"), bbox_inches='tight')
plt.close()
print("✅ Figure 9 saved")

# ---------------------------------------------------------------------------
# Comprehensive Metrics Calculation
# ---------------------------------------------------------------------------
print("\nCalculating comprehensive metrics...")

# Basic metrics
accuracy = accuracy_score(y_true, y_pred)
precision_w = precision_recall_fscore_support(y_true, y_pred, average='weighted', zero_division=0)[0]
recall_w = precision_recall_fscore_support(y_true, y_pred, average='weighted', zero_division=0)[1]
f1_w = precision_recall_fscore_support(y_true, y_pred, average='weighted', zero_division=0)[2]

# Macro averages
precision_m = precision_recall_fscore_support(y_true, y_pred, average='macro', zero_division=0)[0]
recall_m = precision_recall_fscore_support(y_true, y_pred, average='macro', zero_division=0)[1]
f1_m = precision_recall_fscore_support(y_true, y_pred, average='macro', zero_division=0)[2]

# Additional metrics
cohen_kappa = cohen_kappa_score(y_true, y_pred)
mcc = matthews_corrcoef(y_true, y_pred)
hamming = hamming_loss(y_true, y_pred)

# Per-class metrics
precision_per = [report[str(i)]['precision'] for i in range(num_classes)]
recall_per = [report[str(i)]['recall'] for i in range(num_classes)]
f1_per = [report[str(i)]['f1-score'] for i in range(num_classes)]
support_per = [report[str(i)]['support'] for i in range(num_classes)]

# Macro ROC AUC
try:
    roc_auc_macro = roc_auc_score(y_true, y_probs, multi_class='ovr', average='macro')
    roc_auc_weighted = roc_auc_score(y_true, y_probs, multi_class='ovr', average='weighted')
except Exception as e:
    print(f"Warning: Could not compute ROC AUC: {e}")
    roc_auc_macro = 0.0
    roc_auc_weighted = 0.0

# ---------------------------------------------------------------------------
# Save Comprehensive Metrics JSON
# ---------------------------------------------------------------------------
print("\nSaving metrics...")

comprehensive_metrics = {
    "Overall_Metrics": {
        "Accuracy": float(accuracy),
        "Precision_Weighted": float(precision_w),
        "Recall_Weighted": float(recall_w),
        "F1_Score_Weighted": float(f1_w),
        "Precision_Macro": float(precision_m),
        "Recall_Macro": float(recall_m),
        "F1_Score_Macro": float(f1_m),
        "Cohen_Kappa": float(cohen_kappa),
        "Matthews_Correlation_Coefficient": float(mcc),
        "Hamming_Loss": float(hamming),
        "ROC_AUC_Macro": float(roc_auc_macro),
        "ROC_AUC_Weighted": float(roc_auc_weighted),
    },
    "Per_Class_Metrics": {
        class_names[i]: {
            "Precision": float(precision_per[i]),
            "Recall": float(recall_per[i]),
            "F1_Score": float(f1_per[i]),
            "Support": int(support_per[i])
        }
        for i in range(num_classes)
    },
    "Training_Summary": {
        "Best_Validation_Accuracy": float(best_val_acc),
        "Final_Test_Accuracy": float(accuracy),
        "Total_Epochs_Trained": int(len(epochs)),
        "Test_Samples": int(len(y_true)),
    }
}

with open(os.path.join(METRICS_DIR, "comprehensive_metrics.json"), "w") as f:
    json.dump(comprehensive_metrics, f, indent=4)

# Save detailed classification report
detailed_report = classification_report(y_true, y_pred, target_names=class_names, 
                                       digits=4, zero_division=0, output_dict=True)
with open(os.path.join(METRICS_DIR, "detailed_classification_report.json"), "w") as f:
    json.dump(detailed_report, f, indent=4)

# ---------------------------------------------------------------------------
# Save Research Tables (CSV format)
# ---------------------------------------------------------------------------
print("Creating research tables...")

# Table 1: Per-Class Performance
per_class_df = pd.DataFrame({
    'Class': class_names,
    'Precision': precision_per,
    'Recall': recall_per,
    'F1-Score': f1_per,
    'Support': support_per,
    'Accuracy': [accuracy_score(y_true == i, y_pred == i) for i in range(num_classes)]
})
per_class_df.to_csv(os.path.join(TABLES_DIR, "per_class_metrics_table.csv"), index=False)

# Table 2: Training History
training_df = pd.DataFrame({
    'Epoch': epochs,
    'Train_Accuracy': train_acc,
    'Val_Accuracy': val_acc,
    'Test_Accuracy': test_acc,
    'Train_Loss': train_loss,
    'Val_Loss': val_loss,
    'Test_Loss': test_loss,
    'Train_F1': train_f1,
    'Val_F1': val_f1,
    'Test_F1': test_f1,
    'Train_Kappa': train_kappa,
    'Val_Kappa': val_kappa,
    'Test_Kappa': test_kappa,
})
training_df.to_csv(os.path.join(TABLES_DIR, "training_history_table.csv"), index=False)

# Table 3: Overall Metrics Summary
overall_metrics_df = pd.DataFrame({
    'Metric': list(comprehensive_metrics['Overall_Metrics'].keys()),
    'Value': list(comprehensive_metrics['Overall_Metrics'].values())
})
overall_metrics_df.to_csv(os.path.join(TABLES_DIR, "overall_metrics_summary.csv"), index=False)

# ---------------------------------------------------------------------------
# Save Final Dump
# ---------------------------------------------------------------------------
final_dump = {
    "comprehensive_metrics": comprehensive_metrics,
    "confusion_matrix": cm.tolist(),
    "confusion_matrix_normalized": cm_normalized.tolist(),
    "y_true": y_true.tolist(),
    "y_pred": y_pred.tolist(),
    "y_probs": y_probs.tolist(),
    "classification_report": detailed_report,
    "training_history": {
        "epochs": epochs.tolist(),
        "train_acc": train_acc.tolist(),
        "val_acc": val_acc.tolist(),
        "test_acc": test_acc.tolist(),
        "train_loss": train_loss.tolist(),
        "val_loss": val_loss.tolist(),
        "test_loss": test_loss.tolist(),
        "train_f1": train_f1.tolist(),
        "val_f1": val_f1.tolist(),
        "test_f1": test_f1.tolist(),
        "train_kappa": train_kappa.tolist(),
        "val_kappa": val_kappa.tolist(),
        "test_kappa": test_kappa.tolist(),
    }
}

with open(os.path.join(RESULTS_DIR, "all_results_comprehensive.pkl"), "wb") as f:
    pickle.dump(final_dump, f)

# ---------------------------------------------------------------------------
# Generate Research Summary Report
# ---------------------------------------------------------------------------
print("\nGenerating research summary report...")

summary_report = f"""
{'='*80}
COMPREHENSIVE EVALUATION REPORT - BRAIN ACTIVITY CLASSIFICATION
{'='*80}

EXECUTIVE SUMMARY
{'-'*80}
This report presents a comprehensive evaluation of the trained neural network model
for harmful brain activity classification using EEG signals.

MODEL CONFIGURATION
{'-'*80}
- Model Type: {('Wav2Vec2 + BiLSTM' if hasattr(model, 'lstm') else 'Wav2Vec2')}
- Number of Classes: {num_classes}
- Classes: {', '.join(class_names)}
- Training Epochs: {len(epochs)}
- Batch Size: {batch_size}
- Optimizer: AdamW (lr=1e-5)
- Loss Function: {config['criterion_name']} (gamma={config['criterion_kwargs'].get('gamma', 'N/A')})

OVERALL PERFORMANCE METRICS
{'-'*80}
Accuracy:                        {accuracy:.6f}
Precision (Weighted):            {precision_w:.6f}
Recall (Weighted):               {recall_w:.6f}
F1-Score (Weighted):             {f1_w:.6f}
Precision (Macro):               {precision_m:.6f}
Recall (Macro):                  {recall_m:.6f}
F1-Score (Macro):                {f1_m:.6f}
Cohen's Kappa:                   {cohen_kappa:.6f}
Matthews Correlation Coeff:      {mcc:.6f}
Hamming Loss:                    {hamming:.6f}
ROC AUC (Macro):                 {roc_auc_macro:.6f}
ROC AUC (Weighted):              {roc_auc_weighted:.6f}

TRAINING SUMMARY
{'-'*80}
Best Validation Accuracy:        {best_val_acc:.6f}
Final Test Accuracy:             {accuracy:.6f}
Total Samples Tested:            {len(y_true)}
Test Set Composition:
"""

for i, (class_name, support) in enumerate(zip(class_names, support_per)):
    summary_report += f"  {class_name:15s}: {int(support):5d} samples ({support/len(y_true)*100:5.2f}%)\n"

summary_report += f"""
{'-'*80}

PER-CLASS PERFORMANCE
{'-'*80}
{"Class":<15} {"Precision":<12} {"Recall":<12} {"F1-Score":<12} {"Support":<10}
{'-'*80}
"""

for i, class_name in enumerate(class_names):
    summary_report += f"{class_name:<15} {precision_per[i]:<12.6f} {recall_per[i]:<12.6f} {f1_per[i]:<12.6f} {int(support_per[i]):<10}\n"

summary_report += f"""
{'-'*80}

OUTPUT ARTIFACTS
{'-'*80}
Figures Generated:
  ✓ 01_accuracy_loss_curves.png/pdf        - Combined accuracy & loss curves
  ✓ 02_f1_kappa_curves.png/pdf             - F1 score & Cohen's kappa curves
  ✓ 03_confusion_matrix.png/pdf            - Confusion matrix heatmap
  ✓ 04_confusion_matrix_normalized.png/pdf - Normalized confusion matrix
  ✓ 05_per_class_metrics.png/pdf           - Per-class performance bars
  ✓ 06_roc_curves.png/pdf                  - ROC curves (One-vs-Rest)
  ✓ 07_precision_recall_curves.png/pdf     - Precision-Recall curves
  ✓ 08_tsne_visualization.png/pdf          - t-SNE embedding visualization
  ✓ 09_class_distribution.png/pdf          - Class distribution plots

Metrics Files:
  ✓ comprehensive_metrics.json             - All metrics in JSON format
  ✓ detailed_classification_report.json    - Detailed sklearn report

Tables (CSV):
  ✓ per_class_metrics_table.csv            - Per-class metrics
  ✓ training_history_table.csv             - Complete training history
  ✓ overall_metrics_summary.csv            - Overall summary metrics

Data Files:
  ✓ y_true.npy                             - Ground truth labels
  ✓ y_pred.npy                             - Predicted labels
  ✓ y_probs.npy                            - Prediction probabilities
  ✓ tsne_embeddings.npy                    - t-SNE embeddings
  ✓ tsne_labels.npy                        - t-SNE labels
  ✓ all_results_comprehensive.pkl          - Complete results pickle

DIRECTORY STRUCTURE
{'-'*80}
{RESULTS_DIR}/
├── figures/          (9 publication-ready figures in PNG & PDF)
├── metrics/          (JSON metrics and numpy arrays)
├── tables/           (CSV tables for papers)
└── all_results_comprehensive.pkl

{'='*80}
Report Generated: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}
{'='*80}
"""

with open(os.path.join(RESULTS_DIR, "RESEARCH_SUMMARY_REPORT.txt"), "w") as f:
    f.write(summary_report)

print(summary_report)

# ---------------------------------------------------------------------------
# Final Console Summary
# ---------------------------------------------------------------------------
print("\n" + "="*80)
print("✅ RESEARCH-GRADE ANALYSIS COMPLETE!")
print("="*80)
print(f"\n📊 KEY RESULTS:")
print(f"   • Accuracy:              {accuracy:.4f}")
print(f"   • F1-Score (Weighted):   {f1_w:.4f}")
print(f"   • Cohen's Kappa:         {cohen_kappa:.4f}")
print(f"   • ROC AUC (Weighted):    {roc_auc_weighted:.4f}")
print(f"\n📁 OUTPUT DIRECTORIES:")
print(f"   • Figures:   {FIGURES_DIR}")
print(f"   • Metrics:   {METRICS_DIR}")
print(f"   • Tables:    {TABLES_DIR}")
print(f"\n📄 SUMMARY REPORT:")
print(f"   {os.path.join(RESULTS_DIR, 'RESEARCH_SUMMARY_REPORT.txt')}")
print("="*80 + "\n")



# ============================================================================
# EXTENDED INTERPRETABILITY & VISUALIZATION SECTION (ADD TO END OF SCRIPT)
# ============================================================================
# Insert this section AFTER the final console output and before script end

print("\n" + "="*90)
print("ADVANCED INTERPRETABILITY & VISUALIZATION ANALYSIS")
print("="*90 + "\n")

# ============================================================================
# FIGURE 7: ATTENTION WEIGHTS VISUALIZATION
# ============================================================================
print("[10/20] Generating Figure 7: Attention Weights Distribution...")

# Extract attention weights from model
attention_weights_all = []

with torch.no_grad():
    for batch_idx, batch in enumerate(tqdm(test_loader, desc="Extracting attention", leave=False)):
        inputs = test_partition._get_input_kwargs(batch)
        normalized_votes = inputs['normalized_votes']
        del inputs['normalized_votes']
        
        outputs = model(
            input_values=inputs['input_values'],
            attention_mask=None,
            output_attentions=True,
            return_dict=True
        )
        
        if outputs.attentions is not None and len(outputs.attentions) > 0:
            last_attention = outputs.attentions[-1]
            attn_avg = last_attention.mean(dim=1)
            attention_weights_all.append(attn_avg.cpu().numpy())

if attention_weights_all:
    attention_weights = np.concatenate(attention_weights_all, axis=0)
    
    fig, axes = plt.subplots(2, 2, figsize=(14, 12))
    
    mean_attention = attention_weights.mean(axis=0)
    im1 = axes[0, 0].imshow(mean_attention, cmap='hot', aspect='auto')
    axes[0, 0].set_title('Mean Attention Weights Across All Samples', fontsize=12, fontweight='bold')
    axes[0, 0].set_xlabel('Key Position')
    axes[0, 0].set_ylabel('Query Position')
    plt.colorbar(im1, ax=axes[0, 0])
    
    epsilon = 1e-10
    attention_entropy = -np.sum(attention_weights * np.log(attention_weights + epsilon), axis=-1).mean(axis=-1)
    axes[0, 1].hist(attention_entropy, bins=50, color='#2E86AB', edgecolor='black', alpha=0.7)
    axes[0, 1].set_title('Distribution of Attention Entropy', fontsize=12, fontweight='bold')
    axes[0, 1].set_xlabel('Attention Entropy')
    axes[0, 1].set_ylabel('Frequency')
    axes[0, 1].grid(True, alpha=0.3)
    
    attention_max = attention_weights.max(axis=-1).mean(axis=-1)
    axes[1, 0].hist(attention_max, bins=50, color='#A23B72', edgecolor='black', alpha=0.7)
    axes[1, 0].set_title('Distribution of Max Attention Weight', fontsize=12, fontweight='bold')
    axes[1, 0].set_xlabel('Max Attention Weight')
    axes[1, 0].set_ylabel('Frequency')
    axes[1, 0].grid(True, alpha=0.3)
    
    mean_attn_by_pos = attention_weights.mean(axis=0).mean(axis=0)
    axes[1, 1].bar(range(len(mean_attn_by_pos)), mean_attn_by_pos, color='#F18F01', alpha=0.7, edgecolor='black')
    axes[1, 1].set_title('Mean Attention Weight by Position', fontsize=12, fontweight='bold')
    axes[1, 1].set_xlabel('Sequence Position')
    axes[1, 1].set_ylabel('Mean Attention')
    axes[1, 1].grid(True, alpha=0.3, axis='y')
    
    plt.tight_layout()
    plt.savefig(os.path.join(FIGURES_DIR, "07_attention_weights.png"), dpi=300, bbox_inches='tight')
    plt.savefig(os.path.join(FIGURES_DIR, "07_attention_weights.pdf"), bbox_inches='tight')
    plt.close()
    print("✓ Figure 7 saved\n")

# ============================================================================
# FIGURE 8: PREDICTION CONFIDENCE ANALYSIS
# ============================================================================
print("[11/20] Generating Figure 8: Prediction Confidence Analysis...")

pred_confidence = np.max(y_probs, axis=1)
correct_predictions = (y_pred == y_true)

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

axes[0, 0].hist(pred_confidence[correct_predictions], bins=50, alpha=0.7, 
                label='Correct', color='#2E86AB', edgecolor='black')
axes[0, 0].hist(pred_confidence[~correct_predictions], bins=50, alpha=0.7, 
                label='Incorrect', color='#E63946', edgecolor='black')
axes[0, 0].set_title('Prediction Confidence: Correct vs Incorrect', fontsize=12, fontweight='bold')
axes[0, 0].set_xlabel('Confidence Score')
axes[0, 0].set_ylabel('Frequency')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

thresholds = np.linspace(0, 1, 50)
accuracies_by_threshold = []
coverage_by_threshold = []

for threshold in thresholds:
    mask = pred_confidence >= threshold
    if mask.sum() > 0:
        acc = accuracy_score(y_true[mask], y_pred[mask])
        coverage = mask.sum() / len(y_true)
    else:
        acc = 0
        coverage = 0
    accuracies_by_threshold.append(acc)
    coverage_by_threshold.append(coverage)

axes[0, 1].plot(thresholds, accuracies_by_threshold, 'o-', linewidth=2.5, 
                markersize=6, color='#2E86AB', label='Accuracy')
axes_twin = axes[0, 1].twinx()
axes_twin.plot(thresholds, coverage_by_threshold, 's-', linewidth=2.5, 
               markersize=6, color='#F18F01', label='Coverage')
axes[0, 1].set_xlabel('Confidence Threshold', fontsize=11, fontweight='bold')
axes[0, 1].set_ylabel('Accuracy', fontsize=11, fontweight='bold', color='#2E86AB')
axes_twin.set_ylabel('Coverage', fontsize=11, fontweight='bold', color='#F18F01')
axes[0, 1].set_title('Accuracy-Confidence Trade-off', fontsize=12, fontweight='bold')
axes[0, 1].grid(True, alpha=0.3)

from sklearn.calibration import calibration_curve
prob_true, prob_pred = calibration_curve(y_true, y_probs.max(axis=1), n_bins=10)
axes[1, 0].plot([0, 1], [0, 1], 'k--', lw=2, label='Perfectly Calibrated')
axes[1, 0].plot(prob_pred, prob_true, 'o-', linewidth=2.5, markersize=8, 
                color='#2E86AB', label='Model')
axes[1, 0].fill_between(prob_pred, prob_true, prob_pred, alpha=0.2, color='#2E86AB')
axes[1, 0].set_xlabel('Mean Predicted Probability', fontsize=11, fontweight='bold')
axes[1, 0].set_ylabel('True Probability', fontsize=11, fontweight='bold')
axes[1, 0].set_title('Calibration Curve', fontsize=12, fontweight='bold')
axes[1, 0].legend()
axes[1, 0].grid(True, alpha=0.3)

class_confidences = {class_names[i]: pred_confidence[y_pred == i] for i in range(num_classes)}
bp = axes[1, 1].boxplot([class_confidences[cn] for cn in class_names], labels=class_names,
                         patch_artist=True)
for patch in bp['boxes']:
    patch.set_facecolor('#2E86AB')
    patch.set_alpha(0.7)
axes[1, 1].set_ylabel('Prediction Confidence', fontsize=11, fontweight='bold')
axes[1, 1].set_title('Confidence Distribution by Predicted Class', fontsize=12, fontweight='bold')
axes[1, 1].grid(True, alpha=0.3, axis='y')
axes[1, 1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "08_confidence_analysis.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "08_confidence_analysis.pdf"), bbox_inches='tight')
plt.close()
print("✓ Figure 8 saved\n")

# ============================================================================
# FIGURE 9: PREDICTION ERROR ANALYSIS
# ============================================================================
print("[12/20] Generating Figure 9: Prediction Error Analysis...")

errors = y_true != y_pred
error_classes = y_true[errors]
predicted_classes = y_pred[errors]

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

error_counts = np.bincount(error_classes, minlength=num_classes)
axes[0, 0].bar(range(num_classes), error_counts, color='#E63946', alpha=0.7, edgecolor='black')
axes[0, 0].set_xticks(range(num_classes))
axes[0, 0].set_xticklabels(class_names, rotation=45, ha='right')
axes[0, 0].set_ylabel('Number of Errors', fontsize=11, fontweight='bold')
axes[0, 0].set_title('Error Distribution by True Class', fontsize=12, fontweight='bold')
axes[0, 0].grid(True, alpha=0.3, axis='y')

if errors.sum() > 0:
    error_cm = confusion_matrix(y_true[errors], y_pred[errors], labels=range(num_classes))
    sns.heatmap(error_cm, annot=True, fmt="d", cmap="Reds", ax=axes[0, 1],
                xticklabels=class_names, yticklabels=class_names, cbar_kws={'label': 'Error Count'})
    axes[0, 1].set_title('Misclassification Matrix (Errors Only)', fontsize=12, fontweight='bold')
    axes[0, 1].set_xlabel('Predicted Class')
    axes[0, 1].set_ylabel('True Class')

error_rates = []
for i in range(num_classes):
    class_mask = y_true == i
    if class_mask.sum() > 0:
        class_error_rate = (y_true[class_mask] != y_pred[class_mask]).sum() / class_mask.sum()
    else:
        class_error_rate = 0
    error_rates.append(class_error_rate)

axes[1, 0].bar(range(num_classes), error_rates, color='#F18F01', alpha=0.7, edgecolor='black')
axes[1, 0].set_xticks(range(num_classes))
axes[1, 0].set_xticklabels(class_names, rotation=45, ha='right')
axes[1, 0].set_ylabel('Error Rate', fontsize=11, fontweight='bold')
axes[1, 0].set_title('Error Rate by True Class', fontsize=12, fontweight='bold')
axes[1, 0].set_ylim([0, 1])
axes[1, 0].grid(True, alpha=0.3, axis='y')

if errors.sum() > 0:
    error_confidence = pred_confidence[errors]
    correct_confidence = pred_confidence[~errors]
    axes[1, 1].violinplot([correct_confidence, error_confidence], positions=[1, 2], 
                          showmeans=True, showmedians=True)
    axes[1, 1].set_xticks([1, 2])
    axes[1, 1].set_xticklabels(['Correct', 'Incorrect'])
    axes[1, 1].set_ylabel('Prediction Confidence', fontsize=11, fontweight='bold')
    axes[1, 1].set_title('Confidence: Correct vs Misclassified', fontsize=12, fontweight='bold')
    axes[1, 1].grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "09_error_analysis.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "09_error_analysis.pdf"), bbox_inches='tight')
plt.close()
print("✓ Figure 9 saved\n")

# ============================================================================
# FIGURE 10: CLASS DISTRIBUTION & IMBALANCE
# ============================================================================
print("[13/20] Generating Figure 10: Class Distribution & Imbalance Analysis...")

fig = plt.figure(figsize=(16, 10))
gs = GridSpec(2, 3, figure=fig, hspace=0.35, wspace=0.3)

# Plot 1: Training set class distribution
train_class_counts = np.bincount(y_true, minlength=num_classes)[:len(train_meta_df)]
test_class_counts = np.bincount(y_true, minlength=num_classes)

ax1 = fig.add_subplot(gs[0, 0])
bars1 = ax1.bar(range(min(num_classes, len(train_class_counts))), train_class_counts[:num_classes], color='#2E86AB', alpha=0.7, edgecolor='black')
ax1.set_xticks(range(num_classes))
ax1.set_xticklabels(class_names, rotation=45, ha='right')
ax1.set_ylabel('Count', fontsize=11, fontweight='bold')
ax1.set_title('Training Set Class Distribution', fontsize=12, fontweight='bold')
ax1.grid(True, alpha=0.3, axis='y')

# Plot 2: Test set class distribution
ax2 = fig.add_subplot(gs[0, 1])
bars2 = ax2.bar(range(num_classes), test_class_counts, color='#A23B72', alpha=0.7, edgecolor='black')
ax2.set_xticks(range(num_classes))
ax2.set_xticklabels(class_names, rotation=45, ha='right')
ax2.set_ylabel('Count', fontsize=11, fontweight='bold')
ax2.set_title('Test Set Class Distribution', fontsize=12, fontweight='bold')
for bar in bars2:
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height, f'{int(height)}',
            ha='center', va='bottom', fontsize=9, fontweight='bold')
ax2.grid(True, alpha=0.3, axis='y')

# Plot 3: Imbalance ratio
ax3 = fig.add_subplot(gs[0, 2])
imbalance_ratios = test_class_counts / (test_class_counts.max() + 1e-10)
bars3 = ax3.bar(range(num_classes), imbalance_ratios, color='#F18F01', alpha=0.7, edgecolor='black')
ax3.set_xticks(range(num_classes))
ax3.set_xticklabels(class_names, rotation=45, ha='right')
ax3.set_ylabel('Ratio to Max', fontsize=11, fontweight='bold')
ax3.set_title('Class Imbalance Ratio', fontsize=12, fontweight='bold')
ax3.set_ylim([0, 1.1])
ax3.grid(True, alpha=0.3, axis='y')

# Plot 4: Per-class recall
ax4 = fig.add_subplot(gs[1, 0])
recall_per_class = []
for i in range(num_classes):
    class_mask = y_true == i
    if class_mask.sum() > 0:
        recall = (y_pred[class_mask] == i).sum() / class_mask.sum()
    else:
        recall = 0
    recall_per_class.append(recall)

bars4 = ax4.bar(range(num_classes), recall_per_class, color='#2E86AB', alpha=0.7, edgecolor='black')
ax4.set_xticks(range(num_classes))
ax4.set_xticklabels(class_names, rotation=45, ha='right')
ax4.set_ylabel('Recall', fontsize=11, fontweight='bold')
ax4.set_title('Per-Class Recall (Sensitivity)', fontsize=12, fontweight='bold')
ax4.set_ylim([0, 1.1])
ax4.axhline(y=np.mean(recall_per_class), color='red', linestyle='--', linewidth=2, label='Mean')
ax4.grid(True, alpha=0.3, axis='y')
ax4.legend()

# Plot 5: Per-class precision
ax5 = fig.add_subplot(gs[1, 1])
precision_per_class = []
for i in range(num_classes):
    pred_mask = y_pred == i
    if pred_mask.sum() > 0:
        precision = (y_true[pred_mask] == i).sum() / pred_mask.sum()
    else:
        precision = 0
    precision_per_class.append(precision)

bars5 = ax5.bar(range(num_classes), precision_per_class, color='#A23B72', alpha=0.7, edgecolor='black')
ax5.set_xticks(range(num_classes))
ax5.set_xticklabels(class_names, rotation=45, ha='right')
ax5.set_ylabel('Precision', fontsize=11, fontweight='bold')
ax5.set_title('Per-Class Precision (Specificity)', fontsize=12, fontweight='bold')
ax5.set_ylim([0, 1.1])
ax5.axhline(y=np.mean(precision_per_class), color='red', linestyle='--', linewidth=2, label='Mean')
ax5.grid(True, alpha=0.3, axis='y')
ax5.legend()

# Plot 6: F1 Score comparison
ax6 = fig.add_subplot(gs[1, 2])
f1_per_class_val = []
for i in range(num_classes):
    if support_per[i] > 0:
        f1_val = f1_per[i]
    else:
        f1_val = 0
    f1_per_class_val.append(f1_val)

bars6 = ax6.bar(range(num_classes), f1_per_class_val, color='#F18F01', alpha=0.7, edgecolor='black')
ax6.set_xticks(range(num_classes))
ax6.set_xticklabels(class_names, rotation=45, ha='right')
ax6.set_ylabel('F1 Score', fontsize=11, fontweight='bold')
ax6.set_title('Per-Class F1 Score', fontsize=12, fontweight='bold')
ax6.set_ylim([0, 1.1])
ax6.axhline(y=f1_w, color='red', linestyle='--', linewidth=2, label='Weighted Mean')
ax6.grid(True, alpha=0.3, axis='y')
ax6.legend()

plt.savefig(os.path.join(FIGURES_DIR, "10_class_distribution_imbalance.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "10_class_distribution_imbalance.pdf"), bbox_inches='tight')
plt.close()
print("✓ Figure 10 saved\n")

# ============================================================================
# FIGURE 11: EMBEDDING SPACE ANALYSIS (t-SNE)
# ============================================================================
print("[14/20] Generating Figure 11: t-SNE Embedding Analysis...")

embeddings_all = []
with torch.no_grad():
    for batch in tqdm(test_loader, desc="Extracting embeddings", leave=False):
        inputs = test_partition._get_input_kwargs(batch)
        outputs = model(
            input_values=inputs['input_values'],
            output_hidden_states=True,
            return_dict=True
        )
        hidden_states = outputs.last_hidden_state
        pooled = hidden_states.mean(dim=1)
        embeddings_all.append(pooled.cpu().numpy())

embeddings_all = np.concatenate(embeddings_all, axis=0)

print("Running t-SNE (this may take a minute)...")
tsne = TSNE(n_components=2, perplexity=min(30, max(5, (len(embeddings_all)-1)//3)), 
            random_state=42, max_iter=1500, verbose=0)
embeddings_2d = tsne.fit_transform(embeddings_all)

fig, axes = plt.subplots(2, 2, figsize=(16, 14))

scatter1 = axes[0, 0].scatter(embeddings_2d[:, 0], embeddings_2d[:, 1], c=y_true, 
                              cmap='tab10', s=50, alpha=0.6, edgecolors='black', linewidth=0.5)
axes[0, 0].set_title('t-SNE Embedding Space (True Classes)', fontsize=12, fontweight='bold')
axes[0, 0].set_xlabel('t-SNE Dimension 1')
axes[0, 0].set_ylabel('t-SNE Dimension 2')
cbar1 = plt.colorbar(scatter1, ax=axes[0, 0])
cbar1.set_ticks(range(num_classes))
cbar1.set_ticklabels(class_names)
axes[0, 0].grid(True, alpha=0.2)

scatter2 = axes[0, 1].scatter(embeddings_2d[:, 0], embeddings_2d[:, 1], c=y_pred, 
                              cmap='tab10', s=50, alpha=0.6, edgecolors='black', linewidth=0.5)
axes[0, 1].set_title('t-SNE Embedding Space (Predicted Classes)', fontsize=12, fontweight='bold')
axes[0, 1].set_xlabel('t-SNE Dimension 1')
axes[0, 1].set_ylabel('t-SNE Dimension 2')
cbar2 = plt.colorbar(scatter2, ax=axes[0, 1])
cbar2.set_ticks(range(num_classes))
cbar2.set_ticklabels(class_names)
axes[0, 1].grid(True, alpha=0.2)

colors_correct = ['green' if y_true[i] == y_pred[i] else 'red' for i in range(len(y_true))]
axes[1, 0].scatter(embeddings_2d[:, 0], embeddings_2d[:, 1], c=colors_correct, 
                   s=50, alpha=0.6, edgecolors='black', linewidth=0.5)
axes[1, 0].set_title('t-SNE Embedding Space (Correct vs Incorrect)', fontsize=12, fontweight='bold')
axes[1, 0].set_xlabel('t-SNE Dimension 1')
axes[1, 0].set_ylabel('t-SNE Dimension 2')
from matplotlib.patches import Patch
legend_elements = [Patch(facecolor='green', label='Correct'),
                   Patch(facecolor='red', label='Incorrect')]
axes[1, 0].legend(handles=legend_elements, loc='best')
axes[1, 0].grid(True, alpha=0.2)

scatter4 = axes[1, 1].scatter(embeddings_2d[:, 0], embeddings_2d[:, 1], c=pred_confidence, 
                              cmap='RdYlGn', s=50, alpha=0.6, edgecolors='black', linewidth=0.5)
axes[1, 1].set_title('t-SNE Embedding Space (Prediction Confidence)', fontsize=12, fontweight='bold')
axes[1, 1].set_xlabel('t-SNE Dimension 1')
axes[1, 1].set_ylabel('t-SNE Dimension 2')
cbar4 = plt.colorbar(scatter4, ax=axes[1, 1])
cbar4.set_label('Confidence')
axes[1, 1].grid(True, alpha=0.2)

plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "11_tsne_embedding_space.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "11_tsne_embedding_space.pdf"), bbox_inches='tight')
plt.close()
print("✓ Figure 11 saved\n")

# ============================================================================
# FIGURE 12: RECEIVER OPERATING CHARACTERISTIC (ROC) - DETAILED
# ============================================================================
print("[15/20] Generating Figure 12: Detailed ROC Analysis...")

fig, axes = plt.subplots(2, 2, figsize=(16, 14))

# Plot 1: Multi-class ROC (one-vs-rest)
ax = axes[0, 0]
colors_roc = plt.cm.tab10(np.linspace(0, 1, num_classes))
for i in range(num_classes):
    y_bin = (y_true == i).astype(int)
    fpr, tpr, _ = roc_curve(y_bin, y_probs[:, i])
    roc_auc = auc(fpr, tpr)
    ax.plot(fpr, tpr, color=colors_roc[i], lw=2.5, 
            label=f'{class_names[i]} (AUC={roc_auc:.3f})', alpha=0.8)
ax.plot([0, 1], [0, 1], 'k--', lw=2, label='Random', alpha=0.5)
ax.set_xlabel('False Positive Rate', fontsize=11, fontweight='bold')
ax.set_ylabel('True Positive Rate', fontsize=11, fontweight='bold')
ax.set_title('ROC Curves (One-vs-Rest)', fontsize=12, fontweight='bold')
ax.legend(loc='lower right', fontsize=9)
ax.grid(True, alpha=0.3)

# Plot 2: Precision-Recall curves
ax = axes[0, 1]
for i in range(num_classes):
    y_bin = (y_true == i).astype(int)
    precision_i, recall_i, _ = precision_recall_curve(y_bin, y_probs[:, i])
    ax.plot(recall_i, precision_i, color=colors_roc[i], lw=2.5, 
            label=f'{class_names[i]}', alpha=0.8)
ax.set_xlabel('Recall', fontsize=11, fontweight='bold')
ax.set_ylabel('Precision', fontsize=11, fontweight='bold')
ax.set_title('Precision-Recall Curves', fontsize=12, fontweight='bold')
ax.legend(loc='best', fontsize=9)
ax.grid(True, alpha=0.3)

# Plot 3: AUC comparison
ax = axes[1, 0]
auc_scores = []
for i in range(num_classes):
    y_bin = (y_true == i).astype(int)
    fpr, tpr, _ = roc_curve(y_bin, y_probs[:, i])
    auc_score = auc(fpr, tpr)
    auc_scores.append(auc_score)

bars = ax.barh(range(num_classes), auc_scores, color=colors_roc, alpha=0.7, edgecolor='black')
ax.set_yticks(range(num_classes))
ax.set_yticklabels(class_names)
ax.set_xlabel('AUC Score', fontsize=11, fontweight='bold')
ax.set_title('AUC Score by Class', fontsize=12, fontweight='bold')
ax.set_xlim([0, 1.1])
for i, (bar, score) in enumerate(zip(bars, auc_scores)):
    ax.text(score + 0.02, i, f'{score:.3f}', va='center', fontsize=10, fontweight='bold')
ax.grid(True, alpha=0.3, axis='x')

# Plot 4: Sensitivity-Specificity trade-off
ax = axes[1, 1]
sensitivities = []
specificities = []
for i in range(num_classes):
    y_bin = (y_true == i).astype(int)
    tn = ((y_pred != i) & (y_true != i)).sum()
    fp = ((y_pred == i) & (y_true != i)).sum()
    sensitivity = recall_per[i] if i < len(recall_per) else 0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
    sensitivities.append(sensitivity)
    specificities.append(specificity)

x = np.arange(num_classes)
width = 0.35
ax.bar(x - width/2, sensitivities, width, label='Sensitivity', 
       color='#2E86AB', alpha=0.7, edgecolor='black')
ax.bar(x + width/2, specificities, width, label='Specificity', 
       color='#A23B72', alpha=0.7, edgecolor='black')
ax.set_xticks(x)
ax.set_xticklabels(class_names, rotation=45, ha='right')
ax.set_ylabel('Score', fontsize=11, fontweight='bold')
ax.set_title('Sensitivity vs Specificity by Class', fontsize=12, fontweight='bold')
ax.set_ylim([0, 1.1])
ax.legend()
ax.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "12_detailed_roc_analysis.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "12_detailed_roc_analysis.pdf"), bbox_inches='tight')
plt.close()
print("✓ Figure 12 saved\n")

# ============================================================================
# FIGURE 13: LEARNING DYNAMICS & CONVERGENCE
# ============================================================================
print("[16/20] Generating Figure 13: Learning Dynamics & Convergence...")

fig = plt.figure(figsize=(18, 12))
gs = GridSpec(3, 3, figure=fig, hspace=0.4, wspace=0.3)

# Loss trajectories
for plot_idx, (dataset, data, color) in enumerate(zip(['train', 'val', 'test'], 
                                                        [train_loss, val_loss, test_loss],
                                                        ['#2E86AB', '#A23B72', '#F18F01'])):
    ax = fig.add_subplot(gs[0, plot_idx])
    ax.plot(epochs, data, 'o-', linewidth=2.5, markersize=5, color=color)
    ax.set_title(f'{dataset.capitalize()} Loss Trajectory', fontsize=11, fontweight='bold')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Loss')
    ax.grid(True, alpha=0.3)

# F1, Precision, Recall trajectories
for plot_idx, (metric, train_data, val_data, test_data) in enumerate(zip(
    ['F1', 'Precision', 'Recall'],
    [train_f1, [precision_w]*len(epochs), [recall_w]*len(epochs)],
    [val_f1, [precision_w]*len(epochs), [recall_w]*len(epochs)],
    [test_f1, [precision_w]*len(epochs), [recall_w]*len(epochs)])):
    
    ax = fig.add_subplot(gs[1, plot_idx])
    if isinstance(train_data, (list, np.ndarray)):
        ax.plot(epochs, train_data, 'o-', label='Train', color='#2E86AB', linewidth=2.5, markersize=5)
        ax.plot(epochs, val_data, 's-', label='Val', color='#A23B72', linewidth=2.5, markersize=5)
        ax.plot(epochs, test_data, '^-', label='Test', color='#F18F01', linewidth=2.5, markersize=5)
        ax.legend()
    ax.set_title(f'{metric} Trajectory', fontsize=11, fontweight='bold')
    ax.set_xlabel('Epoch')
    ax.set_ylabel(metric)
    ax.grid(True, alpha=0.3)

# Overfitting analysis
ax = fig.add_subplot(gs[2, 0])
val_train_diff = np.array(val_loss) - np.array(train_loss)
ax.fill_between(epochs, 0, val_train_diff, where=(val_train_diff>0), alpha=0.5, 
                color='#E63946', label='Overfitting', step='mid')
ax.fill_between(epochs, 0, val_train_diff, where=(val_train_diff<=0), alpha=0.5, 
                color='#06A77D', label='Underfitting', step='mid')
ax.axhline(y=0, color='black', linestyle='-', linewidth=1)
ax.set_title('Overfitting vs Underfitting', fontsize=11, fontweight='bold')
ax.set_xlabel('Epoch')
ax.set_ylabel('Val Loss - Train Loss')
ax.legend()
ax.grid(True, alpha=0.3)

# Training accuracy delta
ax = fig.add_subplot(gs[2, 1])
train_acc_diff = np.diff(train_acc)
ax.plot(epochs[1:], train_acc_diff, 'o-', color='#2E86AB', linewidth=2, markersize=5)
ax.axhline(y=0, color='red', linestyle='--', linewidth=1, alpha=0.5)
ax.fill_between(epochs[1:], train_acc_diff, 0, where=(train_acc_diff>=0), 
                alpha=0.3, color='#06A77D', label='Improving')
ax.fill_between(epochs[1:], train_acc_diff, 0, where=(train_acc_diff<0), 
                alpha=0.3, color='#E63946', label='Degrading')
ax.set_title('Training Accuracy Delta', fontsize=11, fontweight='bold')
ax.set_xlabel('Epoch')
ax.set_ylabel('Δ Accuracy')
ax.legend()
ax.grid(True, alpha=0.3)

# KL divergence tracking
ax = fig.add_subplot(gs[2, 2])
kl_divs = []
for k, v in sorted(experiment_data.items()):
    if k.startswith('epoch_'):
        kl_div = v['val_metrics'].get('total_kl_loss', 0)
        kl_divs.append(kl_div)
if kl_divs:
    ax.plot(epochs, kl_divs, 'o-', color='#A23B72', linewidth=2.5, markersize=5)
    ax.set_title('KL Divergence (Val Set)', fontsize=11, fontweight='bold')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('KL Loss')
    ax.grid(True, alpha=0.3)

plt.savefig(os.path.join(FIGURES_DIR, "13_learning_dynamics.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "13_learning_dynamics.pdf"), bbox_inches='tight')
plt.close()
print("✓ Figure 13 saved\n")

# ============================================================================
# FIGURE 14 & 15: SUMMARY
# ============================================================================
print("[17/20] Generating Final Summary Figure...")

fig = plt.figure(figsize=(18, 12))
gs = GridSpec(2, 3, figure=fig, hspace=0.3, wspace=0.3)

# Summary metrics
ax = fig.add_subplot(gs[0, 0])
metrics_summary = {
    'Accuracy': accuracy,
    'F1 (Weighted)': f1_w,
    'Precision': precision_w,
    'Recall': recall_w,
    'Kappa': cohen_kappa,
}
ax.barh(list(metrics_summary.keys()), list(metrics_summary.values()), 
        color='#2E86AB', alpha=0.7, edgecolor='black')
ax.set_xlim([0, 1])
ax.set_xlabel('Score', fontsize=11, fontweight='bold')
ax.set_title('Overall Performance Summary', fontsize=12, fontweight='bold')
for i, (k, v) in enumerate(metrics_summary.items()):
    ax.text(v + 0.02, i, f'{v:.3f}', va='center', fontsize=10, fontweight='bold')
ax.grid(True, alpha=0.3, axis='x')

# Class-wise performance
ax = fig.add_subplot(gs[0, 1])
x = np.arange(num_classes)
width = 0.25
ax.bar(x - width, precision_per, width, label='Precision', color='#2E86AB', alpha=0.7, edgecolor='black')
ax.bar(x, recall_per, width, label='Recall', color='#A23B72', alpha=0.7, edgecolor='black')
ax.bar(x + width, f1_per, width, label='F1', color='#F18F01', alpha=0.7, edgecolor='black')
ax.set_xticks(x)
ax.set_xticklabels(class_names, rotation=45, ha='right')
ax.set_ylabel('Score', fontsize=11, fontweight='bold')
ax.set_title('Per-Class Performance', fontsize=12, fontweight='bold')
ax.legend()
ax.grid(True, alpha=0.3, axis='y')

# Model statistics
ax = fig.add_subplot(gs[0, 2])
ax.axis('off')
stats_text = f"""
MODEL STATISTICS

Total Parameters: {sum(p.numel() for p in model.parameters()):,}
Trainable: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}

TRAINING INFO
Epochs Trained: {len(epochs)}
Best Val Acc: {best_val_acc:.4f}
Final Test Acc: {accuracy:.4f}

DATASET
Train: {len(train_meta_df)} samples
Val: {len(val_meta_df)} samples
Test: {len(test_meta_df)} samples

CONFIDENCE STATS
Mean: {pred_confidence.mean():.4f}
Std: {pred_confidence.std():.4f}
Min: {pred_confidence.min():.4f}
Max: {pred_confidence.max():.4f}
"""
ax.text(0.1, 0.5, stats_text, fontsize=10, family='monospace',
        verticalalignment='center', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

# Confusion matrix
ax = fig.add_subplot(gs[1, 0])
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
sns.heatmap(cm_norm, annot=True, fmt='.2%', cmap='Blues', ax=ax,
            xticklabels=class_names, yticklabels=class_names, cbar_kws={'label': 'Accuracy'})
ax.set_title('Normalized Confusion Matrix', fontsize=12, fontweight='bold')
ax.set_xlabel('Predicted')
ax.set_ylabel('True')

# Confidence distribution
ax = fig.add_subplot(gs[1, 1])
ax.hist(pred_confidence[y_pred == y_true], bins=50, alpha=0.7, label='Correct', color='#06A77D', edgecolor='black')
ax.hist(pred_confidence[y_pred != y_true], bins=50, alpha=0.7, label='Incorrect', color='#E63946', edgecolor='black')
ax.set_xlabel('Confidence', fontsize=11, fontweight='bold')
ax.set_ylabel('Frequency', fontsize=11, fontweight='bold')
ax.set_title('Confidence Distribution', fontsize=12, fontweight='bold')
ax.legend()
ax.grid(True, alpha=0.3)

# Top insights
ax = fig.add_subplot(gs[1, 2])
ax.axis('off')
insights_text = f"""
KEY INSIGHTS

✓ Best Class: {class_names[np.argmax(f1_per)]}
  (F1: {max(f1_per):.3f})

⚠ Worst Class: {class_names[np.argmin(f1_per)]}
  (F1: {min(f1_per):.3f})

✓ Highest Confidence: {pred_confidence.max():.3f}
⚠ Lowest Confidence: {pred_confidence.min():.3f}

✓ Error Rate: {errors.sum()/len(y_true)*100:.1f}%
✓ Correct Rate: {(1-errors.sum()/len(y_true))*100:.1f}%

✓ Model is {'CALIBRATED' if abs(pred_confidence.mean()-accuracy) < 0.1 else 'MISCALIBRATED'}
  (Conf-Acc gap: {pred_confidence.mean()-accuracy:.3f})
"""
ax.text(0.05, 0.5, insights_text, fontsize=10, family='monospace',
        verticalalignment='center', bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.5))

plt.savefig(os.path.join(FIGURES_DIR, "14_comprehensive_summary.png"), dpi=300, bbox_inches='tight')
plt.savefig(os.path.join(FIGURES_DIR, "14_comprehensive_summary.pdf"), bbox_inches='tight')
plt.close()
print("✓ Figure 14 saved\n")

# ============================================================================
# FINAL REPORT
# ============================================================================
print("[18/20] Generating Interpretability Report...")

interpretability_report = f"""
{'='*100}
COMPREHENSIVE MODEL INTERPRETABILITY & ANALYSIS REPORT
{'='*100}

EXECUTIVE SUMMARY
{'-'*100}
This report provides deep interpretability analysis for the Wav2Vec2-based EEG classification model.

MODEL PERFORMANCE
{'-'*100}
Accuracy (Test):     {accuracy:.6f}
F1-Score (Weighted): {f1_w:.6f}
Precision (Weighted):{precision_w:.6f}
Recall (Weighted):   {recall_w:.6f}
Cohen's Kappa:       {cohen_kappa:.6f}
ROC AUC (Weighted):  {roc_auc_weighted:.6f}

CONFIDENCE ANALYSIS
{'-'*100}
Mean Confidence:     {pred_confidence.mean():.6f}
Std Confidence:      {pred_confidence.std():.6f}
Calibration Gap:     {(pred_confidence.mean() - accuracy):.6f}
  (Positive = Overconfident, Negative = Underconfident)

High Confidence (>0.9):   {(pred_confidence > 0.9).sum()} samples ({(pred_confidence > 0.9).sum()/len(pred_confidence)*100:.1f}%)
Medium Confidence (0.7-0.9): {((pred_confidence >= 0.7) & (pred_confidence <= 0.9)).sum()} samples
Low Confidence (<0.7):    {(pred_confidence < 0.7).sum()} samples ({(pred_confidence < 0.7).sum()/len(pred_confidence)*100:.1f}%)

ERROR ANALYSIS
{'-'*100}
Total Errors:        {errors.sum()} / {len(y_true)} ({errors.sum()/len(y_true)*100:.2f}%)
Correct Predictions: {(~errors).sum()} / {len(y_true)} ({(~errors).sum()/len(y_true)*100:.2f}%)

Error Distribution:
"""

for i in range(num_classes):
    class_error_count = (error_classes == i).sum()
    interpretability_report += f"  {class_names[i]}: {class_error_count} errors\n"

interpretability_report += f"""

CLASS-WISE ANALYSIS
{'-'*100}
{"Class":<15} {"Precision":<12} {"Recall":<12} {"F1":<12} {"Support":<10}
{'-'*100}
"""

for i in range(num_classes):
    interpretability_report += f"{class_names[i]:<15} {precision_per[i]:<12.4f} {recall_per[i]:<12.4f} {f1_per[i]:<12.4f} {int(support_per[i]):<10}\n"

interpretability_report += f"""

RECOMMENDATIONS
{'-'*100}
1. Model shows {'GOOD' if accuracy > 0.8 else 'FAIR'} overall performance
2. Confidence is {'well-calibrated' if abs(pred_confidence.mean()-accuracy) < 0.1 else 'miscalibrated'}
3. Focus improvement on {class_names[np.argmin(f1_per)]} (lowest F1 score)
4. Consider confidence thresholding at >0.8 for critical applications
5. Collect more data for underperforming classes

{'='*100}
Report Generated: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}
{'='*100}
"""

with open(os.path.join(RESULTS_DIR, "INTERPRETABILITY_REPORT.txt"), "w") as f:
    f.write(interpretability_report)

print(interpretability_report)
print("✓ Interpretability report saved\n")

# ============================================================================
# FINAL OUTPUT
# ============================================================================
print("\n" + "="*90)
print("✅ ADVANCED INTERPRETABILITY ANALYSIS COMPLETE!")
print("="*90)
print(f"\n📊 14 PUBLICATION-READY FIGURES GENERATED:")
print(f"   01-06: Core metrics (Accuracy, Loss, ROC, Confusion Matrices)")
print(f"   07-14: Advanced Interpretability (Attention, Confidence, Errors, Embeddings, etc.)")
print(f"\n📁 ALL OUTPUTS SAVED TO: {RESULTS_DIR}")
print(f"📄 REPORTS: RESEARCH_SUMMARY_REPORT.txt + INTERPRETABILITY_REPORT.txt")
print("="*90 + "\n")